apiVersion : apps/v1
kind: Deployment
metadata:
  name: "terraformaksdevcluster-51f0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "terraformaksdevcluster-51f0"
  template:
    metadata:
      labels:
        app: "terraformaksdevcluster-51f0"
    spec:
      containers:
        - name: "terraformaksdevcluster-51f0"
          image: "acrforaksdemo4.azurecr.io/terraformaksdevcluster"
          ports:
          - containerPort: 80