on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: acrforaksdemo4.azurecr.io
        username: ${{ secrets.acr_acrforaksdemo4_username }}
        password: ${{ secrets.acr_acrforaksdemo4_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t acrforaksdemo4.azurecr.io/terraformaksdevcluster:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push acrforaksdemo4.azurecr.io/terraformaksdevcluster:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_terraformaksdevcluster_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep terraform-aks-dev-cluster9d2b | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace terraform-aks-dev-cluster9d2b`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: terraform-aks-dev-cluster9d2b
        container-registry-url: acrforaksdemo4.azurecr.io
        container-registry-username: ${{ secrets.acr_acrforaksdemo4_username }}
        container-registry-password: ${{ secrets.acr_acrforaksdemo4_password }}
        secret-name: terraformaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: terraform-aks-dev-cluster9d2b
        manifests: |
          manifests/deployment-2.yml
          manifests/service-2.yml
        images: |
          acrforaksdemo4.azurecr.io/terraformaksdevcluster:${{ github.sha }}
        imagepullsecrets: |
          terraformaksdockerauth
